version: '3.8'

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app  # Mount the app directory for live updates
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://ali_rakhshanipour:ali1997313@db:5432/blog_service
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ali_rakhshanipour
      POSTGRES_PASSWORD: ali1997313
      POSTGRES_DB: blog_system
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data:
