# Use the official PostgreSQL 15 Alpine image as the base
FROM postgres:15-alpine

# Set environment variables (optional, can also be set in docker-compose.yml)
ENV POSTGRES_USER=ali_rakhshanipour
ENV POSTGRES_PASSWORD=ali1997313
ENV POSTGRES_DB=blog_service
